import { onNavigate } from '../router.js';
import { nav } from '../components/nav.js';
// import { auth } from '../firebase/config.js';

export const profile = () => {
  /* UN CONTENEDOR Q CONTENGA A LOS BOTONES */
  const div = document.createElement('div');
  const section = document.createElement('div');
  section.innerHTML = `
        <div class="wrapper">
          <div id="nav" class="img-container">
            <img src="./images/Sonder-icon.png" alt="">
          </div>
          <div id="message">
            <h2>404</h2>
            <h1>Page Not Found</h1>
            <p>The specified file was not found on this website. Please check the URL for mistakes and try again.</p>
            <br>
            <h3>Why am I seeing this?</h3>
            <p>This page was generated by the Firebase Command-Line Interface. To modify it, edit the <code>404.html</code> file in your project's configured <code>public</code> directory.</p>
          </div>
       </div>
      `;
  /* FIREBASE */

  const logoCreate = section.querySelector('#nav');
  logoCreate.appendChild(nav());
  logoCreate.addEventListener('click', () => {
    document.querySelector('.nav-container').classList.toggle('show');
  });

  /* AGREGAR TEXTO A LOS BOTONES textContent */


  /* INSERTA append */
  div.append(section);

  return div;
};
